// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: engine_data.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_engine_5fdata_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_engine_5fdata_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_engine_5fdata_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_engine_5fdata_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_engine_5fdata_2eproto;
class EngineData;
struct EngineDataDefaultTypeInternal;
extern EngineDataDefaultTypeInternal _EngineData_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::EngineData* Arena::CreateMaybeMessage<::EngineData>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class EngineData final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:EngineData) */ {
 public:
  inline EngineData() : EngineData(nullptr) {}
  ~EngineData() override;
  explicit PROTOBUF_CONSTEXPR EngineData(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  EngineData(const EngineData& from);
  EngineData(EngineData&& from) noexcept
    : EngineData() {
    *this = ::std::move(from);
  }

  inline EngineData& operator=(const EngineData& from) {
    CopyFrom(from);
    return *this;
  }
  inline EngineData& operator=(EngineData&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const EngineData& default_instance() {
    return *internal_default_instance();
  }
  static inline const EngineData* internal_default_instance() {
    return reinterpret_cast<const EngineData*>(
               &_EngineData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(EngineData& a, EngineData& b) {
    a.Swap(&b);
  }
  inline void Swap(EngineData* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(EngineData* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  EngineData* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<EngineData>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const EngineData& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const EngineData& from) {
    EngineData::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(EngineData* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "EngineData";
  }
  protected:
  explicit EngineData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kRpmFieldNumber = 1,
    kTemperatureFieldNumber = 2,
    kOilPressureFieldNumber = 3,
    kSpeedFieldNumber = 4,
  };
  // int32 rpm = 1;
  void clear_rpm();
  int32_t rpm() const;
  void set_rpm(int32_t value);
  private:
  int32_t _internal_rpm() const;
  void _internal_set_rpm(int32_t value);
  public:

  // int32 temperature = 2;
  void clear_temperature();
  int32_t temperature() const;
  void set_temperature(int32_t value);
  private:
  int32_t _internal_temperature() const;
  void _internal_set_temperature(int32_t value);
  public:

  // int32 oil_pressure = 3;
  void clear_oil_pressure();
  int32_t oil_pressure() const;
  void set_oil_pressure(int32_t value);
  private:
  int32_t _internal_oil_pressure() const;
  void _internal_set_oil_pressure(int32_t value);
  public:

  // int32 speed = 4;
  void clear_speed();
  int32_t speed() const;
  void set_speed(int32_t value);
  private:
  int32_t _internal_speed() const;
  void _internal_set_speed(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:EngineData)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t rpm_;
    int32_t temperature_;
    int32_t oil_pressure_;
    int32_t speed_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_engine_5fdata_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// EngineData

// int32 rpm = 1;
inline void EngineData::clear_rpm() {
  _impl_.rpm_ = 0;
}
inline int32_t EngineData::_internal_rpm() const {
  return _impl_.rpm_;
}
inline int32_t EngineData::rpm() const {
  // @@protoc_insertion_point(field_get:EngineData.rpm)
  return _internal_rpm();
}
inline void EngineData::_internal_set_rpm(int32_t value) {
  
  _impl_.rpm_ = value;
}
inline void EngineData::set_rpm(int32_t value) {
  _internal_set_rpm(value);
  // @@protoc_insertion_point(field_set:EngineData.rpm)
}

// int32 temperature = 2;
inline void EngineData::clear_temperature() {
  _impl_.temperature_ = 0;
}
inline int32_t EngineData::_internal_temperature() const {
  return _impl_.temperature_;
}
inline int32_t EngineData::temperature() const {
  // @@protoc_insertion_point(field_get:EngineData.temperature)
  return _internal_temperature();
}
inline void EngineData::_internal_set_temperature(int32_t value) {
  
  _impl_.temperature_ = value;
}
inline void EngineData::set_temperature(int32_t value) {
  _internal_set_temperature(value);
  // @@protoc_insertion_point(field_set:EngineData.temperature)
}

// int32 oil_pressure = 3;
inline void EngineData::clear_oil_pressure() {
  _impl_.oil_pressure_ = 0;
}
inline int32_t EngineData::_internal_oil_pressure() const {
  return _impl_.oil_pressure_;
}
inline int32_t EngineData::oil_pressure() const {
  // @@protoc_insertion_point(field_get:EngineData.oil_pressure)
  return _internal_oil_pressure();
}
inline void EngineData::_internal_set_oil_pressure(int32_t value) {
  
  _impl_.oil_pressure_ = value;
}
inline void EngineData::set_oil_pressure(int32_t value) {
  _internal_set_oil_pressure(value);
  // @@protoc_insertion_point(field_set:EngineData.oil_pressure)
}

// int32 speed = 4;
inline void EngineData::clear_speed() {
  _impl_.speed_ = 0;
}
inline int32_t EngineData::_internal_speed() const {
  return _impl_.speed_;
}
inline int32_t EngineData::speed() const {
  // @@protoc_insertion_point(field_get:EngineData.speed)
  return _internal_speed();
}
inline void EngineData::_internal_set_speed(int32_t value) {
  
  _impl_.speed_ = value;
}
inline void EngineData::set_speed(int32_t value) {
  _internal_set_speed(value);
  // @@protoc_insertion_point(field_set:EngineData.speed)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_engine_5fdata_2eproto
